apiVersion: apps/v1
kind: Deployment
metadata:
  name: khaddem-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: khaddem-frontend
  template:
    metadata:
      labels:
        app: khaddem-frontend
    spec:
      hostNetwork: true
      containers:
        - name: khaddem-frontend
          image: fedilabidi13/khaddem-frontend:latest
          ports:
            - containerPort: 80
          
